project:
  type: website
  output-dir: docs

website:
  title: "Yayun Jin"
  navbar:
    right:
      - about.qmd
      - diary.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/yayunjin/
  page-footer:
    center: |
      <span class="container"><strong>Â© Yayun Jin 2022 - 2023</strong></span>
    
    background: "#004E4F"
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual